# Snort NIDS Configuration
# Personal Cybersecurity Learning Project


# Network Variables

ipvar HOME_NET [
10.0.10.0/24,
10.0.20.0/24,
172.16.50.0/24,
172.16.60.0/24
]


ipvar EXTERNAL_NET !$HOME_NET


# Protected Servers

ipvar WEB_SERVER 172.16.50.10

ipvar DNS_SERVER 172.16.50.53

ipvar MAIL_SERVER 172.16.50.25

ipvar DATABASE_SERVER 172.16.60.100


# Monitored Ports

portvar HTTP_PORTS [80,443]

portvar DNS_PORTS 53

portvar MAIL_PORTS [25,587]

portvar DATABASE_PORTS 5432


# Rule Path

var RULE_PATH ./rules
